/**
 * Tool-call summary renderer contracts (P2 spec §5.3).
 *
 * Summaries are generated by deterministic frontend rules only — never by an
 * LLM, and never by sending tool payloads anywhere. Each renderer registers
 * the tool names it understands plus input/result summarizers.
 */

export interface ToolRenderContext {
  /** Raw tool name as received (may carry the `check-manage_` prefix). */
  name: string
  /** Name with the `check-manage_` prefix stripped. */
  normalizedName: string
  /** OpenCode-provided title (usually a file path / argument preview). */
  title?: string
  /** Canonical part status: pending/running/completed/error/cancelled/… */
  status?: string
  input?: unknown
  result?: unknown
}

export interface ToolRenderer {
  /** Lowercased tool names handled by this renderer (prefix already stripped). */
  matches: string[]
  /** Human-facing display name; falls back to the raw tool name. */
  displayName?: string
  /** Deterministic action summary derived from the input arguments. */
  inputSummary?: (input: Record<string, unknown>, ctx?: ToolRenderContext) => string | undefined
  /** Deterministic result summary (counts / file names / first line / error). */
  resultSummary?: (result: unknown, ctx?: ToolRenderContext) => string | undefined
  /** Extra sensitive keys masked in raw details (beyond the global list). */
  sensitiveKeys?: string[]
  /** Set false to hide the raw input section entirely. */
  showRawInput?: boolean
}

/** Canonical status text — never color/icon alone (P2 spec §5.2). */
export const TOOL_STATUS_TEXT: Record<string, string> = {
  pending: '等待执行',
  running: '正在执行',
  completed: '已完成',
  error: '执行失败',
  cancelled: '已取消',
  permission: '等待确认',
}
