"""Per-session workspace directory: create, cleanup, path-traversal defense.

Also writes the per-session opencode.json so OpenCode (scoped to this
directory) connects to our MCP server with the session's token. This is how
per-session MCP identity works — OpenCode has no per-session MCP API, only
per-directory config (see spec §12).
"""

import logging
import os
import sys
import json
import shutil
import subprocess
import sys
import time

_NO_WINDOW = 0x08000000 if sys.platform == 'win32' else 0  # CREATE_NO_WINDOW
from pathlib import Path

from config import AI_WORKSPACE_ROOT


# Make the workspace itself a git repo so any file the agent writes anywhere
# under it appears in `git status` — without needing the skill to `git clone`
# something first. The .gitignore below silences the well-known noise dirs.
_DEFAULT_GITIGNORE = """# auto-generated by check-manage AI chat
uploads/
outputs/
.opencode/
node_modules/
.venv/
__pycache__/
*.pyc
.DS_Store
opencode.json
AGENTS.md
"""

# Persistent guidance OpenCode reads as project context. The workspace ROOT is
# already a git repo we use for the 变更文件 panel, so the agent must NOT fight
# it for the root .git — pulling code at the root forces hacky .git grafting that
# leaves `git status` reporting every file as deleted. Cloning into a subdir is
# verified to work cleanly. (Listed in .gitignore so it doesn't show as a change.)
_AGENTS_MD = """# AI 会话工作区说明

这是一个受管的 AI 会话工作区。**根目录本身已经是一个用于「变更文件」跟踪的 git 仓库**
（只提交了一个 `.gitignore` 作基线）。

## 拉取 / 克隆远端代码（重要）

- 需要拉取远端代码时，请 **`git clone <url> <子目录>/` 克隆到一个子目录**，保留它自己的
  `.git`。例如：`git clone https://example.com/x.git ./x`。在该子目录里正常做 git
  操作（改文件、查看 diff），「变更文件」面板会正确显示你的修改。
- **不要**在工作区根目录执行 `git init` / `git clone .` / `git remote add` /
  `git fetch` / `git reset` / `git checkout`，也不要移动或替换根目录的 `.git`——这会
  破坏变更跟踪，并可能让 `git status` 把所有文件误报为「已删除」。

`uploads/` 与 `outputs/` 是平台目录，请勿放置代码。
"""


class WorkspacePathError(ValueError):
    """Raised when a user-supplied path escapes the workspace root."""


def session_path(workspace_root: str, user_id: str, session_id: str) -> Path:
    return Path(workspace_root) / user_id / session_id


def _tree_size_mb(path) -> float:
    """目录树占用（MB，best-effort——并发删除/权限错误按 0 计）。
    接受 str 或 Path（refresh_workspace_bytes 传 DB 里的字符串路径）。"""
    path = Path(path)
    total = 0
    try:
        for f in path.rglob('*'):
            if f.is_file():
                try:
                    total += f.stat().st_size
                except OSError:
                    pass
    except OSError:
        pass
    return total / (1024 * 1024)


def refresh_workspace_bytes(session_id: str, workspace_path: str | None) -> dict:
    """后台刷新单会话的 workspace_bytes 用量并做**单会话**配额判定。

    配额口径（2026-09-28 语义变更）：`AI_WORKSPACE_QUOTA_MB` 限制的是
    **单个会话**工作区的大小，而非用户全部会话合计——创建新会话不再被
    其他会话的占用阻断（用户合计口径曾在生产环境把全部新任务挡在门外）。

    返回 {'bytes': int, 'quotaExceeded': bool}。超限额只落告警日志
    （跨阈值时一次），不做硬中断——是否终止该会话由管理员决定。
    best-effort、只在 worker 收口/每日任务等后台上下文调用——禁止进
    请求路径。"""
    import datetime as _dt
    from config import AI_WORKSPACE_QUOTA_MB
    quota_bytes = (AI_WORKSPACE_QUOTA_MB or 0) * 1024 * 1024
    if not workspace_path or not os.path.isdir(workspace_path):
        return {'bytes': 0, 'quotaExceeded': False}
    try:
        total = int(_tree_size_mb(workspace_path) * 1024 * 1024)
        from db import get_db
        with get_db() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT workspace_bytes FROM ai_execution_usage "
                    "WHERE session_id = %s", (session_id,))
                row = cur.fetchone()
                prev = row[0] if row else None
                cur.execute(
                    "INSERT INTO ai_execution_usage "
                    "  (session_id, workspace_bytes, updated_at) "
                    "VALUES (%s, %s, NOW()) "
                    "ON CONFLICT (session_id) DO UPDATE SET "
                    "  workspace_bytes = EXCLUDED.workspace_bytes, "
                    "  updated_at = NOW()",
                    (session_id, total))
            conn.commit()
    except Exception:
        return {'bytes': 0, 'quotaExceeded': False}
    exceeded = bool(quota_bytes and total > quota_bytes)
    # 跨阈值告警一次（prev 未超 且 现超），不逐回合刷屏
    if exceeded and not (prev is not None and prev > quota_bytes):
        logging.getLogger(__name__).warning(
            'session workspace quota exceeded sid=%s: %dMB > %dMB',
            session_id, total // (1024 * 1024), AI_WORKSPACE_QUOTA_MB)
    return {'bytes': total, 'quotaExceeded': exceeded}


def create_session_workspace(workspace_root: str, user_id: str, session_id: str) -> str:
    p = session_path(workspace_root, user_id, session_id)
    (p / "uploads").mkdir(parents=True, exist_ok=True)
    (p / "outputs").mkdir(parents=True, exist_ok=True)
    # Make the workspace itself a git repo so the "变更文件" panel works even
    # when the user (or a skill) writes files directly under the workspace root
    # without `git clone`-ing first. Best-effort: if git isn't on PATH the
    # session still works, the panel just falls back to "find nested .git" mode.
    gitignore = p / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_DEFAULT_GITIGNORE, encoding="utf-8")
    # Persistent agent guidance (read by OpenCode as project context): clone
    # remote code into a SUBDIR, never fight the root .git.
    agents_md = p / "AGENTS.md"
    if not agents_md.exists():
        agents_md.write_text(_AGENTS_MD, encoding="utf-8")
    if not (p / ".git").exists():
        try:
            subprocess.run(
                ["git", "init", "-q"], cwd=str(p),
                check=False, timeout=10, capture_output=True,
                creationflags=_NO_WINDOW,
            )
            # Commit the auto-generated .gitignore so it doesn't pollute the
            # 变更文件 panel with two perennial "untracked" entries on every
            # new session. -c uses the per-command identity without writing
            # to a global git config.
            subprocess.run(
                ["git", "add", ".gitignore"], cwd=str(p),
                check=False, timeout=10, capture_output=True,
                creationflags=_NO_WINDOW,
            )
            subprocess.run(
                ["git", "-c", "user.name=check-manage",
                 "-c", "user.email=check-manage@local",
                 "commit", "-q", "-m", "init"],
                cwd=str(p), check=False, timeout=10, capture_output=True,
                creationflags=_NO_WINDOW,
            )
        except Exception:
            pass  # fail-open: missing git is non-fatal
    return str(p.resolve())


def reset_session_workspace(workspace_path: str) -> None:
    """清空并重新初始化会话工作区（批任务「重新执行」用，2026-09-29）。

    整目录删除后按新建会话完全一致的骨架重建（uploads/outputs/AGENTS.md/
    git init 初始提交）。staged 输入恢复、.opencode 技能/预置仓库布置由
    worker 派发时的 _prepare_workspace/_provision_workspace/inject_global_skills
    完成——新一轮的初始化路径与新建会话完全同径，上一轮产物不残留。

    **uploads/（用户输入）随备份-恢复保留**：批暂存区有 24h TTL 清扫，
    reexecute 过期的批次时若只依赖 staged 恢复，输入会永久丢失——故
    清空前把 uploads 整体移到工作区外临时目录，骨架重建后原样移回
    （staged 恢复派发时 copy2 覆盖同名，内容一致）。

    注意：不重写 opencode.json——批子会话创建时本就没有该文件（MCP 走
    全局配置），凭空写入带无效 token 的配置反而会破坏新一轮的 MCP。

    Windows 文件占用（杀软/句柄未释放）时重试 3 次，仍失败抛最后异常。
    """
    import tempfile
    p = Path(workspace_path)
    # 1) 备份用户输入（uploads 非空才备份；工作区外暂存，rmtree 不伤及）
    uploads_backup = None
    uploads_dir = p / 'uploads'
    try:
        if uploads_dir.is_dir() and any(uploads_dir.iterdir()):
            uploads_backup = Path(tempfile.mkdtemp(prefix='ws-uploads-'))
            shutil.move(str(uploads_dir), str(uploads_backup / 'uploads'))
    except OSError as e:
        if uploads_backup:
            shutil.rmtree(uploads_backup, ignore_errors=True)
        raise OSError(f'备份 uploads 失败，已取消工作区重置: {e}') from e
    try:
        # 2) 整目录删除（Windows 文件占用重试 3 次；git objects 只读文件经
        # _rm_force chmod 后删除——与 cleanup_session_workspace 同解法）
        if p.exists():
            last = None
            for attempt in range(3):
                try:
                    shutil.rmtree(p, onerror=_rm_force)
                    last = None
                    break
                except OSError as e:
                    last = e
                    time.sleep(0.5 * (attempt + 1))
            if last is not None:
                raise last
        # 3) 骨架重建（不写 opencode.json——见 docstring）
        create_session_workspace(str(p.parent.parent), p.parent.name, p.name)
    except Exception:
        if uploads_backup:
            shutil.rmtree(uploads_backup, ignore_errors=True)
        raise
    # 4) 恢复用户输入（uploads 重建目录先移除，避免 move 嵌套成 uploads/uploads）
    if uploads_backup:
        rebuilt = p / 'uploads'
        if rebuilt.is_dir():
            shutil.rmtree(rebuilt)
        shutil.move(str(uploads_backup / 'uploads'), str(rebuilt))
        shutil.rmtree(uploads_backup, ignore_errors=True)


def _rm_force(func, path, _exc_info):
    """rmtree onerror: chmod read-only out (git internals on Windows) and retry,
    swallowing any final failure so teardown is non-fatal."""
    import stat
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception:
        pass  # best-effort — see cleanup_session_workspace docstring


def cleanup_session_workspace(workspace_root: str, user_id: str, session_id: str) -> None:
    p = session_path(workspace_root, user_id, session_id)
    if p.exists():
        # Best-effort: a shared OpenCode process may still hold a handle on the
        # workspace (Windows then raises PermissionError) and the per-session
        # .git/ contains read-only objects. Use an onerror handler that strips
        # the read-only bit and retries, but never lets teardown raise.
        shutil.rmtree(p, onerror=_rm_force)


def cleanup_batch_workspaces(workspace_root: str, user_id: str, sessions: list) -> None:
    """Best-effort teardown of every child session's workspace belonging to a
    batch. Shared by both the internal batch routes (routes/ai_chat_batches.py)
    and the external open-API batch routes (routes/open_api_batches.py) so
    there's exactly one place that knows how to tear down a batch's workspaces.

    Callers MUST run this BEFORE deleting the batch's DB rows (see
    batch_repo.delete_batch's docstring) — once those rows are gone there's no
    way to recover which session ids need their workspace directories removed.

    `sessions` is the list of session dicts as returned by
    `batch_repo.get_batch_detail(...)['sessions']` (each needs an `id` key).
    A single session's cleanup failure (e.g. a held file handle) never blocks
    the others — matches `cleanup_session_workspace`'s own best-effort contract.

    Sweeps BOTH the unified and the legacy batch root: batches created before
    the root unification keep their workspaces under the legacy tree, and a
    delete must not leak those directories.
    """
    roots = {os.path.abspath(r) for r in (workspace_root, legacy_batch_workspace_root())}
    for s in sessions:
        for root in roots:
            try:
                cleanup_session_workspace(root, user_id, s['id'])
            except Exception:
                pass  # best-effort


def write_opencode_config(workspace_path: str, *, mcp_name: str, mcp_url: str,
                          model: str = "", extra_mcp: dict | None = None,
                          include_internal: bool = True) -> str:
    """Write opencode.json into the workspace so OpenCode (scoped to this dir)
    connects to our MCP server at `mcp_url` (which carries the session token)
    and, when given, uses `model` ("<providerID>/<modelID>").

    `extra_mcp` is an optional map of additional OpenCode MCP entries (admin-
    registered external MCP servers) merged in alongside the platform's own; the
    platform entry (`mcp_name`) always wins so external config can't shadow it.
    `include_internal=False` (admin disabled the internal MCP in AI settings)
    omits the platform entry entirely — external entries are still written.
    Callers pass `utils.mcp_servers.internal_mcp_enabled()`; the flag only
    affects newly written configs, existing workspaces are never rewritten.
    Returns the config file path.
    """
    mcp = {}
    if include_internal:
        mcp[mcp_name] = {
            "type": "remote",
            "url": mcp_url,
            "enabled": True,
        }
    if extra_mcp:
        for name, entry in extra_mcp.items():
            if name != mcp_name:           # never let an external entry shadow ours
                mcp[name] = entry
    cfg = {
        "$schema": "https://opencode.ai/config.json",
        "mcp": mcp,
    }
    if model:
        cfg["model"] = model
    cfg_path = Path(workspace_path) / "opencode.json"
    cfg_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    return str(cfg_path)


def ensure_batch_permissions(workspace_path: str) -> str | None:
    """批任务/无人值守子会话：写项目级 opencode.json 允许读取工作区之外的
    文件（`permission.external_directory: "allow"`，项目配置覆盖全局）。

    背景（2026-09-30）：OpenCode 默认 `external_directory: ask`——无人值守
    会话读工作区外的文件会触发授权询问，无人应答 → 工具调用无限挂起（生产
    实测 read 挂 900s 被看门狗 abort）。绑定批任务：派发时在工作区写 allow，
    读外部文件直接成功；全局配置保持 deny，交互会话不受影响。

    幂等合并：文件已存在时只补 permission 键，不动其余内容（防覆盖会话的
    MCP/model 配置）；permission 已是目标值时不重写（避免无谓 mtime 抖动）。
    写失败 best-effort——回落到全局 deny：外部读取会被快速拒绝（不挂死），
    只是能力受限。返回配置文件路径（写失败返回 None）。
    """
    target = {"external_directory": "allow"}
    try:
        cfg_path = Path(workspace_path) / "opencode.json"
        cfg = {}
        if cfg_path.exists():
            cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
            if not isinstance(cfg, dict):
                cfg = {}
        if (cfg.get("permission") or {}).get("external_directory") == "allow":
            return str(cfg_path)
        perm = cfg.get("permission") if isinstance(cfg.get("permission"), dict) else {}
        perm.update(target)
        cfg["permission"] = perm
        cfg_path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2),
                            encoding="utf-8")
        return str(cfg_path)
    except (OSError, ValueError) as e:
        logging.getLogger(__name__).warning(
            "batch permission config write failed ws=%s: %s", workspace_path, e)
        return None


def safe_resolve(root: str, rel_path: str) -> str:
    """Resolve `rel_path` under `root`; raise WorkspacePathError if it escapes.

    Uses os.path.isabs() instead of Path.is_absolute() to correctly detect
    Unix-style absolute paths (e.g. '/etc/passwd') on Windows, where
    Path('/etc/passwd').is_absolute() incorrectly returns False.
    """
    root_p = Path(root).resolve()
    if os.path.isabs(rel_path):
        raise WorkspacePathError("absolute path not allowed")
    target = (root_p / rel_path).resolve()
    try:
        target.relative_to(root_p)
    except ValueError:
        raise WorkspacePathError(f"path escapes workspace: {rel_path}")
    return str(target)


def batch_workspace_root() -> str:
    """Root for batch-task child workspaces and batch/scan staging.

    Batch code historically used its own env var (AI_CHAT_WORKSPACE_ROOT)
    defaulting to a cwd-relative 'ai-workspaces', which silently diverged from
    AI_WORKSPACE_ROOT (default ~/.check-manage/ai-workspaces) where chat
    sessions and global-skills live — batch children then injected global
    skills from a different (stale) directory than the admin upload UI writes
    to. The default is now the shared AI_WORKSPACE_ROOT; the old env var still
    wins when explicitly set (existing deployments keep their layout).
    """
    return os.environ.get('AI_CHAT_WORKSPACE_ROOT') or AI_WORKSPACE_ROOT


def legacy_batch_workspace_root() -> str:
    """Where batch data lived before the root unification: the old default was
    a cwd-relative 'ai-workspaces', i.e. <server pkg dir>/ai-workspaces under
    `npm run server` (cd server). Read-only fallback — old staged files and
    child workspaces are still resolved/cleaned here so no data migration is
    needed; nothing new is ever created here.
    """
    return str(Path(__file__).resolve().parent.parent / 'ai-workspaces')


def batch_roots() -> list:
    """[unified root, legacy root] deduped by resolved path, new data first."""
    out, seen = [], set()
    for r in (batch_workspace_root(), legacy_batch_workspace_root()):
        key = os.path.abspath(r).lower() if os.name == 'nt' else os.path.abspath(r)
        if key not in seen:
            seen.add(key)
            out.append(r)
    return out


def resolve_batch_data_path(rel_path: str, roots=None) -> str:
    """Resolve a stored batch-relative path (staged input / scan context dir)
    across the unified and legacy roots — old pending sessions keep working
    without migration. Raises FileNotFoundError if neither root has it."""
    for root in (roots if roots is not None else batch_roots()):
        p = Path(root) / rel_path
        if p.exists():
            return str(p)
    raise FileNotFoundError(f'输入文件不存在或已被清理: {rel_path}')


def batch_staging_dir(workspace_root: str, user_id: str,
                      upload_session_id: str) -> Path:
    """Return (and create) the staging dir for a not-yet-created batch.

    Lives under <workspace_root>/batch-staging/<user_id>/<upload_session_id>/.
    The staged file is **copied** (shutil.copy2 / copytree, see
    batch_engine._prepare_workspace) into the per-session workspace when the
    worker actually runs the child — NOT moved, and not at batch-creation time.
    So the staging dir survives the whole batch lifecycle and is only reclaimed
    by the TTL sweep (routes/open_api_batches._sweep_stale_staging).
    """
    # sanitize the upload_session_id (allow uuids/letters/digits/hyphens only)
    safe = ''.join(ch for ch in upload_session_id
                   if ch.isalnum() or ch in '-_')
    if not safe:
        raise WorkspacePathError("invalid upload_session_id")
    p = Path(workspace_root) / "batch-staging" / user_id / safe
    p.mkdir(parents=True, exist_ok=True)
    return p


def validate_staged_files(files, user_id: str) -> str | None:
    """Internal (JWT) counterpart of open_api_batches._validate_staged_path.

    The UI create/append endpoints used to accept any files[].path — an
    absolute path or one under batch-staging/<someone-else>/ let a logged-in
    user have the worker copy arbitrary readable files into their own
    workspace, where the AI (and the file panels) would expose them. Every
    path must be relative, `..`-free, and land inside
    batch-staging/<this user>/ under one of the batch roots; the file must
    also currently exist (TTL sweep may have removed it).

    Returns a Chinese error message, or None when every file is acceptable.
    """
    from pathlib import PurePosixPath
    if not files:
        return None
    for f in files:
        path = str((f or {}).get('path') or '').replace('\\', '/')
        if not path or path.startswith('/') or os.path.isabs(path):
            return '文件路径无效'
        parts = PurePosixPath(path).parts
        if any(p == '..' for p in parts):
            return '文件路径无效'
        if len(parts) < 3 or parts[0] != 'batch-staging' \
                or parts[1] != user_id:
            return '文件路径无效'
        if not any(os.path.isfile(os.path.join(r, path)) for r in batch_roots()):
            return f'文件「{(f or {}).get("name") or path}」已过期或不存在，请重新上传'
    return None


def reclaim_expired_workspaces(now=None) -> int:
    """P1 §9.3：回收超过保留期的**终态批次**子会话工作区（默认 30 天）。

    只清目录、不动 DB 行（审计与 results 契约不受影响）；mtime 以目录自身
    时间戳近似（批次终态后不再有写入）。返回回收个数。best-effort。"""
    import datetime as _dt
    import os as _os
    from config import AI_WORKSPACE_RETENTION_DAYS
    if not AI_WORKSPACE_RETENTION_DAYS or AI_WORKSPACE_RETENTION_DAYS <= 0:
        return 0
    now = now or _dt.datetime.now()
    cutoff = now - _dt.timedelta(days=AI_WORKSPACE_RETENTION_DAYS)
    reclaimed = 0
    root = _workspace_root_global()
    if not root or not _os.path.isdir(root):
        return 0
    from db import get_db
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT s.id, s.workspace_path FROM ai_chat_sessions s "
                "JOIN ai_chat_batches b ON b.id = s.batch_id "
                "WHERE s.workspace_path IS NOT NULL "
                "  AND b.status IN ('completed','failed','partial') "
                "  AND b.completed_at < %s LIMIT 500",
                (cutoff,))
            rows = cur.fetchall()
    for sid, ws in rows:
        try:
            if not ws or not _os.path.isdir(ws):
                continue
            mtime = _dt.datetime.fromtimestamp(_os.path.getmtime(ws))
            if mtime > cutoff:
                continue
            import shutil as _shutil
            _shutil.rmtree(ws, ignore_errors=True)
            if not _os.path.isdir(ws):
                reclaimed += 1
        except Exception:
            continue
    return reclaimed


def _workspace_root_global():
    try:
        from config import AI_WORKSPACE_ROOT
        return AI_WORKSPACE_ROOT
    except Exception:
        return None