"""Per-session workspace directory: create, cleanup, path-traversal defense.

Also writes the per-session opencode.json so OpenCode (scoped to this
directory) connects to our MCP server with the session's token. This is how
per-session MCP identity works — OpenCode has no per-session MCP API, only
per-directory config (see spec §12).
"""

import os
import json
import shutil
import subprocess
from pathlib import Path


# Make the workspace itself a git repo so any file the agent writes anywhere
# under it appears in `git status` — without needing the skill to `git clone`
# something first. The .gitignore below silences the well-known noise dirs.
_DEFAULT_GITIGNORE = """# auto-generated by check-manage AI chat
uploads/
outputs/
.opencode/
node_modules/
.venv/
__pycache__/
*.pyc
.DS_Store
opencode.json
"""


class WorkspacePathError(ValueError):
    """Raised when a user-supplied path escapes the workspace root."""


def session_path(workspace_root: str, user_id: str, session_id: str) -> Path:
    return Path(workspace_root) / user_id / session_id


def create_session_workspace(workspace_root: str, user_id: str, session_id: str) -> str:
    p = session_path(workspace_root, user_id, session_id)
    (p / "uploads").mkdir(parents=True, exist_ok=True)
    (p / "outputs").mkdir(parents=True, exist_ok=True)
    # Make the workspace itself a git repo so the "变更文件" panel works even
    # when the user (or a skill) writes files directly under the workspace root
    # without `git clone`-ing first. Best-effort: if git isn't on PATH the
    # session still works, the panel just falls back to "find nested .git" mode.
    gitignore = p / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_DEFAULT_GITIGNORE, encoding="utf-8")
    if not (p / ".git").exists():
        try:
            subprocess.run(
                ["git", "init", "-q"], cwd=str(p),
                check=False, timeout=10, capture_output=True,
            )
            # Commit the auto-generated .gitignore so it doesn't pollute the
            # 变更文件 panel with two perennial "untracked" entries on every
            # new session. -c uses the per-command identity without writing
            # to a global git config.
            subprocess.run(
                ["git", "add", ".gitignore"], cwd=str(p),
                check=False, timeout=10, capture_output=True,
            )
            subprocess.run(
                ["git", "-c", "user.name=check-manage",
                 "-c", "user.email=check-manage@local",
                 "commit", "-q", "-m", "init"],
                cwd=str(p), check=False, timeout=10, capture_output=True,
            )
        except Exception:
            pass  # fail-open: missing git is non-fatal
    return str(p.resolve())


def _rm_force(func, path, _exc_info):
    """rmtree onerror: chmod read-only out (git internals on Windows) and retry,
    swallowing any final failure so teardown is non-fatal."""
    import stat
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception:
        pass  # best-effort — see cleanup_session_workspace docstring


def cleanup_session_workspace(workspace_root: str, user_id: str, session_id: str) -> None:
    p = session_path(workspace_root, user_id, session_id)
    if p.exists():
        # Best-effort: a shared OpenCode process may still hold a handle on the
        # workspace (Windows then raises PermissionError) and the per-session
        # .git/ contains read-only objects. Use an onerror handler that strips
        # the read-only bit and retries, but never lets teardown raise.
        shutil.rmtree(p, onerror=_rm_force)


def write_opencode_config(workspace_path: str, *, mcp_name: str, mcp_url: str,
                          model: str = "") -> str:
    """Write opencode.json into the workspace so OpenCode (scoped to this dir)
    connects to our MCP server at `mcp_url` (which carries the session token)
    and, when given, uses `model` ("<providerID>/<modelID>").
    Returns the config file path.
    """
    cfg = {
        "$schema": "https://opencode.ai/config.json",
        "mcp": {
            mcp_name: {
                "type": "remote",
                "url": mcp_url,
                "enabled": True,
            },
        },
    }
    if model:
        cfg["model"] = model
    cfg_path = Path(workspace_path) / "opencode.json"
    cfg_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    return str(cfg_path)


def safe_resolve(root: str, rel_path: str) -> str:
    """Resolve `rel_path` under `root`; raise WorkspacePathError if it escapes.

    Uses os.path.isabs() instead of Path.is_absolute() to correctly detect
    Unix-style absolute paths (e.g. '/etc/passwd') on Windows, where
    Path('/etc/passwd').is_absolute() incorrectly returns False.
    """
    root_p = Path(root).resolve()
    if os.path.isabs(rel_path):
        raise WorkspacePathError("absolute path not allowed")
    target = (root_p / rel_path).resolve()
    try:
        target.relative_to(root_p)
    except ValueError:
        raise WorkspacePathError(f"path escapes workspace: {rel_path}")
    return str(target)


def batch_staging_dir(workspace_root: str, user_id: str,
                      upload_session_id: str) -> Path:
    """Return (and create) the staging dir for a not-yet-created batch.

    Lives under <workspace_root>/batch-staging/<user_id>/<upload_session_id>/
    and is moved into per-session workspaces when the batch is created.
    """
    # sanitize the upload_session_id (allow uuids/letters/digits/hyphens only)
    safe = ''.join(ch for ch in upload_session_id
                   if ch.isalnum() or ch in '-_')
    if not safe:
        raise WorkspacePathError("invalid upload_session_id")
    p = Path(workspace_root) / "batch-staging" / user_id / safe
    p.mkdir(parents=True, exist_ok=True)
    return p
